---

- block:
    - when: dokuwiki_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
  tags:
    - setup-all
    - setup-dokuwiki
    - install-all
    - install-dokuwiki

- block:
    - when: dokuwiki_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-dokuwiki
    - install-all
    - install-dokuwiki

- block:
    - when: not dokuwiki_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-dokuwiki