---

- name: Check existence of dokuwiki systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ dokuwiki_identifier }}.service"
  register: dokuwiki_service_stat

- when: dokuwiki_service_stat.stat.exists | bool
  block:
    - name: Ensure dokuwiki systemd service is stopped
      ansible.builtin.service:
        name: "{{ dokuwiki_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure dokuwiki systemd service does not exists
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ dokuwiki_identifier }}.service"
        state: absent

    - name: Ensure dokuwiki path doesn't exist
      ansible.builtin.file:
        path: "{{ dokuwiki_base_path }}"
        state: absent